//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTimerWinFormsApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Project 1")]
        public string P1_Name_Setting {
            get {
                return ((string)(this["P1_Name_Setting"]));
            }
            set {
                this["P1_Name_Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Project 2")]
        public string P2_Name_Setting {
            get {
                return ((string)(this["P2_Name_Setting"]));
            }
            set {
                this["P2_Name_Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Project 3")]
        public string P3_Name_Setting {
            get {
                return ((string)(this["P3_Name_Setting"]));
            }
            set {
                this["P3_Name_Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Project 4")]
        public string P4_Name_Setting {
            get {
                return ((string)(this["P4_Name_Setting"]));
            }
            set {
                this["P4_Name_Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Project 5")]
        public string P5_Name_Setting {
            get {
                return ((string)(this["P5_Name_Setting"]));
            }
            set {
                this["P5_Name_Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Project 6")]
        public string P6_Name_Setting {
            get {
                return ((string)(this["P6_Name_Setting"]));
            }
            set {
                this["P6_Name_Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Project 7")]
        public string P7_Name_Setting {
            get {
                return ((string)(this["P7_Name_Setting"]));
            }
            set {
                this["P7_Name_Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Project 8")]
        public string P8_Name_Setting {
            get {
                return ((string)(this["P8_Name_Setting"]));
            }
            set {
                this["P8_Name_Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan Total_TimeElapsed_Setting {
            get {
                return ((global::System.TimeSpan)(this["Total_TimeElapsed_Setting"]));
            }
            set {
                this["Total_TimeElapsed_Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan P1_TimeElapsed_Setting {
            get {
                return ((global::System.TimeSpan)(this["P1_TimeElapsed_Setting"]));
            }
            set {
                this["P1_TimeElapsed_Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan P2_TimeElapsed_Setting {
            get {
                return ((global::System.TimeSpan)(this["P2_TimeElapsed_Setting"]));
            }
            set {
                this["P2_TimeElapsed_Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan P3_TimeElapsed_Setting {
            get {
                return ((global::System.TimeSpan)(this["P3_TimeElapsed_Setting"]));
            }
            set {
                this["P3_TimeElapsed_Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan P4_TimeElapsed_Setting {
            get {
                return ((global::System.TimeSpan)(this["P4_TimeElapsed_Setting"]));
            }
            set {
                this["P4_TimeElapsed_Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan P5_TimeElapsed_Setting {
            get {
                return ((global::System.TimeSpan)(this["P5_TimeElapsed_Setting"]));
            }
            set {
                this["P5_TimeElapsed_Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan P6_TimeElapsed_Setting {
            get {
                return ((global::System.TimeSpan)(this["P6_TimeElapsed_Setting"]));
            }
            set {
                this["P6_TimeElapsed_Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan P7_TimeElapsed_Setting {
            get {
                return ((global::System.TimeSpan)(this["P7_TimeElapsed_Setting"]));
            }
            set {
                this["P7_TimeElapsed_Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan P8_TimeElapsed_Setting {
            get {
                return ((global::System.TimeSpan)(this["P8_TimeElapsed_Setting"]));
            }
            set {
                this["P8_TimeElapsed_Setting"] = value;
            }
        }
    }
}
